### ISSUE TITLE
Evaluation Scripts

### ISSUE THREAD

**Issue by Friedrich-M** [JarrentWu1031/SC4D#6]
Thanks for your great work! I wonder if you could provide the evaluation script for SC4D including the temporal error (Temp) and CLIP metric.

Thanks!

**Comment by JarrentWu1031** [comment]
> Thanks for your great work! I wonder if you could provide the evaluation script for SC4D including the temporal error (Temp) and CLIP metric.
> 
> Thanks!

Hi Friedrich! Thanks for your appreciation! Regarding the evaluation script, we haven't organized it previously. I will find some time in the near future to organize the evaluation script and upload it.

**Comment by Friedrich-M** [comment]
Thanks for your reply! I am also curious about the implementation of control points. I noticed that in the original implementation of SC-GS, they used hyper-coordinate (3 for XYZ and rest for feature dims) to both the control points and 3D Gaussians. But in SC4D, there is only xyz coordinate. Is there any special consideration for designing this?

**Comment by JarrentWu1031** [comment]
> Thanks for your reply! I am also curious about the implementation of control points. I noticed that in the original implementation of SC-GS, they used hyper-coordinate (3 for XYZ and rest for feature dims) to both the control points and 3D Gaussians. But in SC4D, there is only xyz coordinate. Is there any special consideration for designing this?

Hi Friedrich! I'm not sure if I understand your question correctly. In fact, the parameters of control points (Gaussians) in our first stage also include quaternion, sh params, opacity and scaling. And in the second stage, the control points' positions, quaternions are utilized for manipulating surface Gaussians. We also consider the control radius of each points as in SC-GS. Since SC-GS was not open-sourced when we initially conducted this research, some of our implementations may differ from SC-GS.

**Comment by Friedrich-M** [comment]
Thanks a lot for your reply!
